services:

#AdonisJS Service
  microservice_smart_lighting_arroio_sim:
    container_name: microservice_smart_lighting_arroio_sim
    build:
      context: .
      dockerfile: Dockerfile
      target: development

    restart: unless-stopped
    env_file:
      - .env
    tty: true
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules/
    ports:
      - ${PORT}:${PORT}

    networks:
      - mirari-iluminacao-server_app-network

#Docker Networks
networks:
  mirari-iluminacao-server_app-network:
    external: true